// export const products = {
//   "countries": ["China", "Bangladesh", "India", "Vietnam", "Indonesia", "Thailand", "Pakistan", "Malaysia", "USA", "Germany"],
//   "industries": ["Apparel", "Electronics", "Textiles", "Pharmaceuticals", "Machinery", "Paper", "Furniture", "Plastics", "Printing", "Metalworking"],
//   "certifications": ["ROHS", "STANDARD", "ISO 9001", "CE", "GMP", "UL", "FSC", "REACH", "ISO 14001", "Oeko-Tex", "ASME", "FDA", "ISO 22000"],
//   "products": [
//     {
//       "id": 1,
//       "product_name": "Smartphone Cover",
//       "price": 5.99,
//       "website": "example.com/product-1",
//       "country": "China",
//       "contact_data": "Chat Now | Contact Supplier",
//       "manufacturing_capabilities": "OEM service available",
//       "certifications": ["ROHS", "CE"],
//       "customer_reviews": "4.5 stars | 120 reviews",
//       "industries_served": ["Electronics"],
//       "company_metadata": {
//         "image": "path/to/product-1.jpg",
//         "min_order": "10 pieces"
//       },
//       "annual_revenue": 150000,
//       "reliability_score": 4.7
//     },
//     {
//       "id": 2,
//       "product_name": "Cotton T-Shirt",
//       "price": 12.5,
//       "website": "example.com/product-2",
//       "country": "Bangladesh",
//       "contact_data": "Contact Supplier",
//       "manufacturing_capabilities": "Customization",
//       "certifications": ["ISO 9001", "Oeko-Tex"],
//       "customer_reviews": "4.3 stars | 95 reviews",
//       "industries_served": ["Apparel"],
//       "company_metadata": {
//         "image": "path/to/product-2.jpg",
//         "min_order": "50 pieces"
//       },
//       "annual_revenue": 90000,
//       "reliability_score": 4.5
//     },
//     {
//       "id": 3,
//       "product_name": "Textile Fabric",
//       "price": 8.99,
//       "website": "example.com/product-3",
//       "country": "India",
//       "contact_data": "Chat Now",
//       "manufacturing_capabilities": "Full production",
//       "certifications": ["CE", "ISO 14001"],
//       "customer_reviews": "4.8 stars | 110 reviews",
//       "industries_served": ["Textiles"],
//       "company_metadata": {
//         "image": "path/to/product-3.jpg",
//         "min_order": "100 meters"
//       },
//       "annual_revenue": 200000,
//       "reliability_score": 4.6
//     },
//     {
//       "id": 4,
//       "product_name": "Medical Syringes",
//       "price": 6.2,
//       "website": "example.com/product-4",
//       "country": "USA",
//       "contact_data": "Contact Supplier",
//       "manufacturing_capabilities": "OEM, ODM",
//       "certifications": ["FDA", "GMP"],
//       "customer_reviews": "4.7 stars | 85 reviews",
//       "industries_served": ["Pharmaceuticals"],
//       "company_metadata": {
//         "image": "path/to/product-4.jpg",
//         "min_order": "500 pieces"
//       },
//       "annual_revenue": 300000,
//       "reliability_score": 4.9
//     },
//     {
//       "id": 5,
//       "product_name": "Industrial Machine Parts",
//       "price": 35.0,
//       "website": "example.com/product-5",
//       "country": "Germany",
//       "contact_data": "Chat Now | Contact Supplier",
//       "manufacturing_capabilities": "Assembly",
//       "certifications": ["ISO 9001", "UL"],
//       "customer_reviews": "4.4 stars | 60 reviews",
//       "industries_served": ["Machinery"],
//       "company_metadata": {
//         "image": "path/to/product-5.jpg",
//         "min_order": "5 units"
//       },
//       "annual_revenue": 500000,
//       "reliability_score": 4.8
//     },
//     {
//       "id": 6,
//       "product_name": "Eco-Friendly Paper Bags",
//       "price": 2.5,
//       "website": "example.com/product-6",
//       "country": "China",
//       "contact_data": "Chat Now",
//       "manufacturing_capabilities": "Packaging",
//       "certifications": ["FSC", "ISO 14001"],
//       "customer_reviews": "4.6 stars | 200 reviews",
//       "industries_served": ["Paper"],
//       "company_metadata": {
//         "image": "path/to/product-6.jpg",
//         "min_order": "1000 pieces"
//       },
//       "annual_revenue": 180000,
//       "reliability_score": 4.7
//     },
//     {
//       "id": 7,
//       "product_name": "Wooden Furniture Set",
//       "price": 250.0,
//       "website": "example.com/product-7",
//       "country": "Indonesia",
//       "contact_data": "Contact Supplier",
//       "manufacturing_capabilities": "Finishing",
//       "certifications": ["REACH"],
//       "customer_reviews": "4.2 stars | 45 reviews",
//       "industries_served": ["Furniture"],
//       "company_metadata": {
//         "image": "path/to/product-7.jpg",
//         "min_order": "3 sets"
//       },
//       "annual_revenue": 70000,
//       "reliability_score": 4.3
//     },
//     {
//       "id": 8,
//       "product_name": "Plastic Molding Components",
//       "price": 18.75,
//       "website": "example.com/product-8",
//       "country": "Thailand",
//       "contact_data": "Chat Now | Contact Supplier",
//       "manufacturing_capabilities": "Molding",
//       "certifications": ["ISO 14001"],
//       "customer_reviews": "4.8 stars | 98 reviews",
//       "industries_served": ["Plastics"],
//       "company_metadata": {
//         "image": "path/to/product-8.jpg",
//         "min_order": "50 pieces"
//       },
//       "annual_revenue": 130000,
//       "reliability_score": 4.6
//     },
//     {
//       "id": 9,
//       "product_name": "Custom Printed T-Shirts",
//       "price": 9.99,
//       "website": "example.com/product-9",
//       "country": "Pakistan",
//       "contact_data": "Chat Now",
//       "manufacturing_capabilities": "Printing",
//       "certifications": ["Oeko-Tex", "ISO 9001"],
//       "customer_reviews": "4.5 stars | 110 reviews",
//       "industries_served": ["Printing"],
//       "company_metadata": {
//         "image": "path/to/product-9.jpg",
//         "min_order": "20 pieces"
//       },
//       "annual_revenue": 95000,
//       "reliability_score": 4.5
//     },
//     {
//       "id": 10,
//       "product_name": "Welding Tools",
//       "price": 45.5,
//       "website": "example.com/product-10",
//       "country": "Malaysia",
//       "contact_data": "Contact Supplier",
//       "manufacturing_capabilities": "Welding",
//       "certifications": ["ASME", "ISO 22000"],
//       "customer_reviews": "4.6 stars | 80 reviews",
//       "industries_served": ["Metalworking"],
//       "company_metadata": {
//         "image": "path/to/product-10.jpg",
//         "min_order": "10 sets"
//       },
//       "annual_revenue": 250000,
//       "reliability_score": 4.7
//     }
//   ]
// }


// // export const products = [
// //   {
// //     id: 1,
// //     product_name: "Product A",
// //     price: 4.75,
// //     website: "example.com/product-a",
// //     country: "China",
// //     contact_data: "Chat Now | Contact Supplier",
// //     manufacturing_capabilities: "OEM service available",
// //     certifications: "ROHS, STANDARD",
// //     customer_reviews: "4.5 stars | 10 reviews",
// //     industries_served: "Apparel",
// //     company_metadata: {
// //       image: "path/to/product-a-image.jpg",
// //       min_order: "2 pieces",
// //     },
// //     annual_revenue: 100000,
// //     reliability_score: 4.8,
// //   },
// //   {
// //     id: 2,
// //     product_name: "Product B",
// //     price: 12.5,
// //     website: "example.com/product-b",
// //     country: "Bangladesh",
// //     contact_data: "Contact Supplier",
// //     manufacturing_capabilities: "Customization",
// //     certifications: "ISO 9001",
// //     customer_reviews: "4.2 stars | 25 reviews",
// //     industries_served: "Electronics",
// //     company_metadata: {
// //       image: "path/to/product-b-image.jpg",
// //       min_order: "5 pieces",
// //     },
// //     annual_revenue: 50000,
// //     reliability_score: 4.5,
// //   },
// //   {
// //     id: 3,
// //     product_name: "Product C",
// //     price: 8.99,
// //     website: "example.com/product-c",
// //     country: "China",
// //     contact_data: "Chat Now",
// //     manufacturing_capabilities: "Full production",
// //     certifications: "CE",
// //     customer_reviews: "4.9 stars | 15 reviews",
// //     industries_served: "Textiles",
// //     company_metadata: {
// //       image: "path/to/product-c-image.jpg",
// //       min_order: "1 piece",
// //     },
// //     annual_revenue: 200000,
// //     reliability_score: 4.7,
// //   },
// //   {
// //     id: 4,
// //     product_name: "Product D",
// //     price: 6.2,
// //     website: "example.com/product-d",
// //     country: "India",
// //     contact_data: "Contact Supplier",
// //     manufacturing_capabilities: "OEM, ODM",
// //     certifications: "GMP",
// //     customer_reviews: "4.6 stars | 30 reviews",
// //     industries_served: "Pharmaceuticals",
// //     company_metadata: {
// //       image: "path/to/product-d-image.jpg",
// //       min_order: "10 pieces",
// //     },
// //     annual_revenue: 75000,
// //     reliability_score: 4.3,
// //   },
// //   {
// //     id: 5,
// //     product_name: "Product E",
// //     price: 15.0,
// //     website: "example.com/product-e",
// //     country: "Vietnam",
// //     contact_data: "Chat Now | Contact Supplier",
// //     manufacturing_capabilities: "Assembly",
// //     certifications: "UL",
// //     customer_reviews: "4.4 stars | 20 reviews",
// //     industries_served: "Machinery",
// //     company_metadata: {
// //       image: "path/to/product-e-image.jpg",
// //       min_order: "3 pieces",
// //     },
// //     annual_revenue: 120000,
// //     reliability_score: 4.6,
// //   },
// //   {
// //     id: 6,
// //     product_name: "Product F",
// //     price: 9.5,
// //     website: "example.com/product-f",
// //     country: "China",
// //     contact_data: "Chat Now",
// //     manufacturing_capabilities: "Packaging",
// //     certifications: "FSC",
// //     customer_reviews: "4.7 stars | 18 reviews",
// //     industries_served: "Paper",
// //     company_metadata: {
// //       image: "path/to/product-f-image.jpg",
// //       min_order: "8 pieces",
// //     },
// //     annual_revenue: 90000,
// //     reliability_score: 4.8,
// //   },
// //   {
// //     id: 7,
// //     product_name: "Product G",
// //     price: 7.8,
// //     website: "example.com/product-g",
// //     country: "Indonesia",
// //     contact_data: "Contact Supplier",
// //     manufacturing_capabilities: "Finishing",
// //     certifications: "REACH",
// //     customer_reviews: "4.3 stars | 22 reviews",
// //     industries_served: "Furniture",
// //     company_metadata: {
// //       image: "path/to/product-g-image.jpg",
// //       min_order: "6 pieces",
// //     },
// //     annual_revenue: 60000,
// //     reliability_score: 4.4,
// //   },
// //   {
// //     id: 8,
// //     product_name: "Product H",
// //     price: 11.2,
// //     website: "example.com/product-h",
// //     country: "Thailand",
// //     contact_data: "Chat Now | Contact Supplier",
// //     manufacturing_capabilities: "Molding",
// //     certifications: "ISO 14001",
// //     customer_reviews: "4.8 stars | 28 reviews",
// //     industries_served: "Plastics",
// //     company_metadata: {
// //       image: "path/to/product-h-image.jpg",
// //       min_order: "4 pieces",
// //     },
// //     annual_revenue: 150000,
// //     reliability_score: 4.7,
// //   },
// //   {
// //     id: 9,
// //     product_name: "Product I",
// //     price: 5.5,
// //     website: "example.com/product-i",
// //     country: "Pakistan",
// //     contact_data: "Chat Now",
// //     manufacturing_capabilities: "Printing",
// //     certifications: "Oeko-Tex",
// //     customer_reviews: "4.5 stars | 12 reviews",
// //     industries_served: "Printing",
// //     company_metadata: {
// //       image: "path/to/product-i-image.jpg",
// //       min_order: "9 pieces",
// //     },
// //     annual_revenue: 40000,
// //     reliability_score: 4.5,
// //   },
// //   {
// //     id: 10,
// //     product_name: "Product J",
// //     price: 13.8,
// //     website: "example.com/product-j",
// //     country: "Malaysia",
// //     contact_data: "Contact Supplier",
// //     manufacturing_capabilities: "Welding",
// //     certifications: "ASME",
// //     customer_reviews: "4.6 stars | 26 reviews",
// //     industries_served: "Metalworking",
// //     company_metadata: {
// //       image: "path/to/product-j-image.jpg",
// //       min_order: "7 pieces",
// //     },
// //     annual_revenue: 180000,
// //     reliability_score: 4.6,
// //   },
// // ];